### ISSUE TITLE
ImportError: bad magic number in 'stock.spiders.topStockSpider': b'\x03\xf3\r\n'

### ISSUE THREAD

**Issue by SeekPoint** [mizhdi/stockSpider#1]
C:\ub16_prj\stockSpider>scrapy crawl stock
Traceback (most recent call last):
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\Scripts\scrapy.exe\__main__.py", line 9, in <module>
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\crawler.py", line 249, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\crawler.py", line 336, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\site-packages\scrapy\utils\misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "c:\users\andyy\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1005, in get_code
  File "<frozen importlib._bootstrap_external>", line 458, in _classify_pyc
ImportError: bad magic number in 'stock.spiders.topStockSpider': b'\x03\xf3\r\n'

C:\ub16_prj\stockSpider>

**Comment by SeekPoint** [comment]
缺少topStockSpider.py文件
